spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans
---
spring:
  zipkin:
    base-url: http://zipkin.monitoring.svc.cluster.local:9411
  sleuth:
    sampler:
      probability: 1.0